function S = bl_suites(name)
% bl_suites(name) -- short test lists, each built around ONE question.
%
%The full registry (bl_cases) is ~40 cases and several hours with the 2-D and % CC, 09/26/2026 (was)
% The full registry (bl_cases) is ~35 cases and several hours with the 2-D and % CC, 09/26/2026
% scaling rows, which is not something to run per change. These lists are cut
% by WHAT THEY TEST, so a change is checked by the list whose question it can
% break. Lists overlap deliberately: a case belongs to every question it
% answers.
%
% Cost is dominated by what is solved, not by how many cases there are. Every
% 1-D case solves in 4-115 ms (measured); the cost of a 1-D list is ~45 s of
% MATLAB startup plus ~1-3 s of PDE->PIE conversion per case. 2-D objective
% cases are 283-574 s EACH and the scaling rungs reach 118 s, so those lists are
% for questions that genuinely need them.
%
% Called with no argument, returns every suite; with a name, just that one.
%
%   smoke       Is the pipeline alive?                           ~1 min
%   structure   Did a core change alter ANY assembled program?   ~2 min
%   executives  Does every executive family still run?           ~1 min
%   known_fail  Did a change fix, or silently move, a failure?   ~1 min
%   nonlinear   Is the PIESOS path (separate code chain) intact? ~5 min
%   twod        2-D assembly and the psatz generators            ~5 min
%  objective2d The expensive 2-D objective executives           ~28 min     % CC, 09/26/2026 (was)
%   objective2d The expensive 2-D objective executives           ~27 min    % CC, 09/26/2026
%   scaling     Solver comparison and size questions ONLY        ~3.5 min
%
% CC, 09/26/2026: H2 dropped from the testing regime (maintainer decision):
%   its ids are removed from structure (22 -> 16), executives (9 -> 7),
%   known_fail (4 -> 2) and objective2d (4 -> 3); the old lines are kept in a
%   comment above each list. Times re-summed from the measured per-case times
%   in results/2026-09-24 (bl_mosek.tsv, check_structure.tsv), not re-run.
%   known_fail no longer holds a trivial-point (rel_b = 1, clean status) case.
% CC, 09/27/2026: three lists for the Sol campaign, check = 'cuadmm': they are
%   run by bl_regime / sol_harness.slurm on copied dumps, NEVER by bl_check,
%   which would build scale_stab_n24/n32 through the executive (a 45 / 142 GB
%   Mosek solve) and cannot build the off-registry ids; bl_check refuses them.
%     sol_compare   desktop vs Sol on clean cases with a known answer
%     sol_large     size and capability, truth by construction or none
%     problematic   known defects or limits, kept apart for investigation
%   Chosen by a read-only census of every case (09-27, with a line-level
%   verification pass); per-case reasons, evidence and the open questions are
%   in SUITES.md, section "Sol lists".

L = struct('name',{},'question',{},'ids',{},'check',{},'why',{});

L(end+1) = mk('smoke', 'Is the pipeline alive?', ...
  {'stab_rd1','stabpde_rd1','hinf_rd1','wellposed_rd1'}, 'structure', ...
  ['One case per STRUCTURAL SHAPE the SDP extraction handles differently: ' ...
   'free variables present (stab_rd1, K.f=43), no free variables at all ' ...
   '(stabpde_rd1, K.f=0), an objective with lpi_ineq, which makes sossolve add ' ...
   'blocks DURING the solve via addextrasosvar (hinf_rd1), and two positive ' ...
   'operators with an O(1) right-hand side (wellposed_rd1, ||b||=17.7, where ' ...
   'every other feasibility case sits at eppos2 ~ 1e-6). A break in any one ' ...
   'of those code paths shows up here.']);

% CC, 09/26/2026: H2 ids dropped (see header). Was:
%  'h2c_rd1','h2cco_rd1','h2o_rd1','h2oco_rd1', ...
%  'est_rd1','h2est_rd1','ctrl_rd1','h2ctrl_rd1','wellposed_rd1'}, 'structure', ...
%  'was cleared (identical on all cases). All 22 together solve in ~1 s; the ' ...
%  'list costs startup and conversion, not solving.']);
L(end+1) = mk('structure', 'Did a core change alter any assembled program?', ...
  {'stab_rd1','stabdual_rd1','stabpde_rd1','stabpded_rd1','stab_rd1_hv', ...
   'stab_rd1_tight','stab_tr1','stab_wave1', ...
   'hinf_rd1','hinfco_rd1','hinfdu_rd1','hinfduco_rd1','hinf_rd1_hv', ...
   'est_rd1','ctrl_rd1','wellposed_rd1'}, 'structure', ...
  ['Every 1-D executive case. m, K.f, the block list and nnz(At) are compared ' ...
   'EXACTLY against the banked baseline: a change to dpvar, opvar, poslpivar, ' ...
   'lpi_eq or lpivar that alters any assembled program changes one of these, ' ...
   'and none of them depends on solver luck. This is how the lpi_eq nnz fix ' ...
   'was cleared (identical on all 22 cases, H2 then included). All 16 ' ...
   'together solve in ~1 s; the list costs startup and conversion, not solving.']); % CC, 09/26/2026

% CC, 09/26/2026: H2 dropped (see header). Was:
%  {'stab_rd1','stabpde_rd1','hinf_rd1','hinfdu_rd1','h2c_rd1','h2o_rd1', ...
%   'Hinf primal and dual, H2 in both gramians, estimator, controller, ' ...
L(end+1) = mk('executives', 'Does every executive family still run?', ...
  {'stab_rd1','stabpde_rd1','hinf_rd1','hinfdu_rd1', ...
   'est_rd1','ctrl_rd1','wellposed_rd1'}, 'runs', ...
  ['One case per executive FAMILY: stability in the Q form and the direct form, ' ...
   'Hinf primal and dual, estimator, controller, ' ...
   'well-posedness. Checks only that each builds and solves -- the ' ...
   'change-an-executive list. Use structure when the change is below the ' ...
   'executives.']);                                                         % CC, 09/26/2026

% CC, 09/26/2026: H2 dropped (see header). h2cco_rd1 was the only 1-D
% trivial-point sentinel (rel_b = 1 with numerr = 0); none remains. Was:
%  {'h2cco_rd1','hinfduco_rd1','ctrl_rd1','h2ctrl_rd1'}, 'sentinel', ...
%   'expected result is the failure. h2cco_rd1 returns rel_b = 1.000 with ' ...
%   'numerr = 0 (the status word does not catch it); hinfduco_rd1 returns ' ...
%   'gam = 8251.9; the two controllers sit at rel_b ~1e-3 with ||x|| ~ 7e7. ' ...
L(end+1) = mk('known_fail', 'Did a change fix, or silently move, a failure?', ...
  {'hinfduco_rd1','ctrl_rd1'}, 'sentinel', ...
  ['The 1-D cases whose CURRENT behaviour is a documented failure, so the ' ...
   'expected result is the failure. hinfduco_rd1 returns gam = 8251.9; ' ...
   'ctrl_rd1 sits at rel_b ~1e-3 with ||x|| ~ 7e7. ' ...
   'A change that repairs one of these is news, and a change that moves one ' ...
   'WITHOUT repairing it is also news -- neither is visible to a pass/fail ' ...
   'suite that only reports the passing cases.']);                          % CC, 09/26/2026

L(end+1) = mk('nonlinear', 'Is the PIESOS path intact?', ...
  {'nl_fisher_opt','nl_fisher_gamfix','nl_fisher_nobnd'}, 'structure', ...
  ['The polyopvar/PIESOS chain is a SEPARATE code path from the LPI executives ' ...
   '(it was broken by a one-character typo in innerprod.m that nothing in the ' ...
   'linear suite could see). Three problem forms of the Fisher local-stability ' ...
   'test at R = 4: objective, gamma fixed, and bound dropped -- which differ in ' ...
   'K.f and block count. ~35-60 s each.']);

L(end+1) = mk('twod', '2-D assembly and the psatz generators', ...
  {'stab2_rd','stab2dual_rd','stab2_rd_psz','stab2_rd_psz90'}, 'structure', ...
  ['2-D stability, psatz off and with the four linear generators ' ...
   '(eq_use_psatz = [3;4;5;6]). Psatz off, Mosek FAILS (rel_b 2.08) where ' ...
   'SeDuMi certifies, so these two rows are sentinels for the solver as much ' ...
   'as for the formulation. With the generators Mosek certifies at 1e-08 at ' ...
   '0.50 and 0.90 lam*, so those two are the regression for poslpivar_2d. ' ...
   '~15-100 s each.']);

% CC, 09/26/2026: H2 dropped (see header). Was:
%  {'hinf2_rd','hinf2nc_rd','hinf2du_rd','h2_2dc_rd'}, 'sentinel', ...
%  ['The 2-D Hinf and H2 executives. 283-574 s EACH, so only when a change ' ...
%   'All four are currently poor or trivial under Mosek.']);
L(end+1) = mk('objective2d', 'The expensive 2-D objective executives', ...
  {'hinf2_rd','hinf2nc_rd','hinf2du_rd'}, 'sentinel', ...
  ['The 2-D Hinf executives. 283-574 s EACH, so only when a change ' ...
   'touches the 2-D objective code. hinf2_rd is the only case in the suite ' ...
   'with an external ground truth (closed-form gain 0.1711, returned 1.272). ' ...
   'All three are currently poor under Mosek.']);                           % CC, 09/26/2026

L(end+1) = mk('scaling', 'Solver comparison and size questions ONLY', ...
  {'scale_stab_n02','scale_stab_n04','scale_stab_n08','scale_stab_n16'}, 'structure', ...
  ['The decoupled-state ladder, m = 135 n^2 exactly. Mosek at n=16 is 118 s ' ...
   'and n>=24 exhausts 64 GB, so this list answers questions about solvers ' ...
   'and scale, never about correctness -- the structure list already covers ' ...
   'the same executive at n=1. n=24 and n=32 are in bl_big.m, not here, ' ...
   'because they cannot be solved by the Mosek arm at all.']);

% CC, 09/27/2026 (start): Sol lists (header).
L(end+1) = mk('sol_compare', 'Does Sol reproduce the desktop on clean, known-answer cases?', ...
  {'stab_tr1','stab_rd1_hv','stab_rd1_tight','stab_wave1', ...
   'hinf_rd1_hv','hinf_rd1','hinfdu_rd1','sent101_f1p010000', ...
   'scale_stab_n08','scale_stab_n16'}, 'cuadmm', ...
  ['Every case here is certified on the desktop by cuADMM under the certified ' ...
   'standard and has a Mosek-certified answer. stab_tr1 is the cheapest ' ...
   'certified case (smoke). stab_rd1_hv is the ladder anchor. stab_rd1_tight ' ...
   'is near the boundary (0.95 lam*, 2.7x the iterations at the same m). ' ...
   'stab_wave1 is the largest certified 1-D feasibility case (m 520). ' ...
   'hinf_rd1_hv, hinf_rd1 and hinfdu_rd1 are the H-inf primal and dual ' ...
   'bisections (1.0002x and 1.0016x Mosek), and _hv also has a held-out ' ...
   'infeasible control. sent101 is infeasible by theorem (negative control). ' ...
   'scale_stab n08/n16 are the Mosek-verified top of the ladder.']);
L(end+1) = mk('sol_large', 'How far does cuADMM go, and at what cost?', ...
  {'scale_stab_n24','scale_stab_n32','scale_sent_f1p01_n16', ...
   'scale_sent_f1p01_n24','scale_sent_f1p01_n32','scale_hinf_n08', ...
   'stab2_rd_psz','Th_n3'}, 'cuadmm', ...
  ['scale_stab is n DECOUPLED copies: iterations are n-invariant (519 to 1e-4 ' ...
   'at n = 1..32, 4023 to 1e-6 at n = 1..16), so it measures memory and cost ' ...
   'per iteration at size, not convergence of a coupled problem. The answer ' ...
   'is known by construction (feasible) or by theory (the 1.01 lam* ' ...
   'sentinels, built by bl_big). scale_hinf_n08 is the largest objective case ' ...
   'with a Mosek bracket (m 17,025). stab2_rd_psz is 2-D with a Mosek-certified F ' ...
   'that cuADMM has not reached (10k it). Th_n3 is m = 80,550 with 26.1M nnz ' ...
   'and no known answer: a size point, not a correctness case.']);
L(end+1) = mk('problematic', 'Known defects and limits, kept apart for investigation', ...
  {'hinfco_rd1','hinfduco_rd1','ctrl_rd1','est_rd1','wellposed_rd1', ...
   'stabpde_rd1','nl_fisher_opt','nl_fisher_gamfix','stab2_rd', ...
   'stab2_rd_psz90','hinf2_rd','hinf2nc_rd','hinf2du_rd','scale_hinf_n04'}, 'cuadmm', ...
  ['Each would waste Sol time or confuse a comparison. The kinds are an ' ...
   'accuracy limit (hinfco, nl_fisher_*, and stabpde and wellposed on the ' ...
   'tolerance edge), a suspected formulation defect (hinfduco, ctrl), unknown ' ...
   'truth (est_rd1, stab2_rd), reference-solver failure (the 2-D objective ' ...
   'executives), never run through the harness (psz90), and transient ' ...
   'non-invariance (scale_hinf_n04). SUITES.md gives the question to ' ...
   'investigate for each.']);
% CC, 09/27/2026 (end)

if nargin >= 1 && ~isempty(name)
    k = find(strcmp({L.name},name));
    if isempty(k)
        error('bl_suites:name','unknown suite "%s"; known: %s',name,strjoin({L.name},', '));
    end
    S = L(k);
else
    S = L;
end
end

function s = mk(name,question,ids,check,why)
s = struct('name',name,'question',question,'ids',{ids},'check',check,'why',why);
end
