function P = subsasgn(P,s,varargin)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% P = SUBSASGN(P,S,VAL) assigns into a 'copvar': dot assignment is the
% builtin, paren assignment P(...) = VAL is an error.
%
% INPUTS
% - P:    'copvar' object, or [] when P(...) = VAL creates a variable;
% - s:    substruct of the indexing expression, generated by MATLAB;
% - varargin: the value(s) assigned; more than one for a comma-list
%           assignment such as [P.C{1:2}] = deal(a,b);
%
% OUTPUTS
% - P:    the modified object.
%
% NOTES
% Why an error: the builtin Q(1,2) = P builds a 1 x 2 ARRAY of copvar
% objects, on which the overloaded 'size' and every container method then
% fail or misread it; nothing in the class accepts an object array.
% Q(1) = P, Q(:) = P and Q(1) = [] are rejected with it. Blocks are
% assigned with P.C{i,j} = X, unchanged. Assigning a container INTO a cell
% or a struct field (c{k} = P, s.f = P) does not call this method.
%
% Cost (measured, R2025b): called for every assignment into a copvar
% outside the class methods, 12-14 us each, independent of q.
% - A direct edit of a local container is in place: P.dim_out(1) = k, and
%   P.C{i,j} = X, which replaces the block without copying it.
% - A NESTED indexed edit into a block, P.C{i,j}.params{k}(r,c) = v, also
%   calls the block's own subsasgn with the block as a shared temporary,
%   which COPIES the edited leaf on every assignment: O(numel) of params{k}
%   (1.07 ms on a 22.9 MB params{1}, against 8 us without the overloads;
%   see @sopvar/subsasgn).
% - For such an edit, extract, clear, edit, reinsert, which edits the
%   block in place (65 us on that params{1}):
%       X = P.C{i,j};  P.C{i,j} = [];  X.params{k}(r,c) = v;  P.C{i,j} = X;
%
% See also SUBSREF, COPVAR.
%
% For support, contact M. Peet, Arizona State University at mpeet@asu.edu

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PIETOOLS - subsasgn(copvar)
%
% Copyright (C) 2026 PIETOOLS Team
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% If you modify this code, document all changes carefully and include date
% authorship, and a brief description of modifications
%
% Initial coding MMP, 09/29/2026. Q(1,2) = P built an object array (see
%                NOTES); it is now an error.

if strcmp(s(1).type,'()')
    error('copvar:parenAssign',['Paren assignment P(...) = X is not '...
        'supported for copvar: it would build an array of containers or '...
        'index one, which no container method accepts. Assign block (i,j) '...
        'with P.C{i,j} = X.'])
end
% The builtin called from this method has the class's own access, so it
% would set protected properties that P.name = X outside the class may
% not. Raise the builtin's error for them, same identifier and text
% (measured). Names come from the metaclass, once.
persistent hidden
if ~iscell(hidden)
    mc = ?copvar;   pl = mc.PropertyList;
    hidden = {pl(~cellfun(@(a) isequal(a,'public'),{pl.SetAccess})).Name};
end
if strcmp(s(1).type,'.') && any(strcmp(s(1).subs,hidden))
    error(message('MATLAB:class:SetProhibited',s(1).subs,'''copvar'''))
end
P = builtin('subsasgn',P,s,varargin{:});

end
