function varargout = subsref(P,s)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% VARARGOUT = SUBSREF(P,S) indexes a 'copvar': dot and brace indexing are
% the builtin, paren indexing P(...) is an error.
%
% INPUTS
% - P:  'copvar' object;
% - s:  substruct of the indexing expression, generated by MATLAB;
%
% OUTPUTS
% - varargout: what the builtin returns, with the caller's nargout.
%
% NOTES
% Why an error: without this method, P(1), P(1,1), P(:), P(1,:) are the
% builtin indexing of a scalar object and return P itself, so code that
% slices an operator by components - C1(1,:) on an 'opvar' in the demos -
% silently received the whole container. Component indexing of containers
% is not implemented: it needs an 'end' over total component counts and a
% decision on how a component range cuts a block row. Until then P(...)
% errors. A block is P.C{i,j}.
%
% '.' and '{}' pass the whole chain to the builtin, which still dispatches
% to the blocks' own subsref (P.C{i,j}(k,l) slices block (i,j)). The
% caller's nargout is the builtin count, set by 'numArgumentsFromSubscript',
% so comma lists ({P.C{:}}, [a,b] = P.C{1:2}) are as before; without that
% method the default count is 1 and a comma list is silently cut to its
% first element (measured, R2025b).
%
% A comma list read through a block, {P.C{i,j}.params{:}}, is served by
% the block's subsref with the same count (@sopvar/@sdopvar subsref,
% 09/29/2026; it raised MATLAB:TooManyOutputs before).
%
% Cost (measured, R2025b): MATLAB calls this for every indexing expression
% on a copvar outside the class methods; inside them the builtin is used.
% 12-14 us per call, against 0.006-0.3 us for the builtin, independent of
% q. A build makes 333-906 calls to the new overloads, flat in q (the same
% count from q = 495 to 3.8e6) and growing with the number of block
% operations and with the 3^N gamma cells: 3% of a 1-D build by count x
% per-call cost, +3-5% by 1-D wall time; below 0.3% of a 2-D or 3-D build.
%
% See also SUBSASGN, NUMARGUMENTSFROMSUBSCRIPT, COPVAR, @sopvar/SUBSREF.
%
% For support, contact M. Peet, Arizona State University at mpeet@asu.edu

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PIETOOLS - subsref(copvar)
%
% Copyright (C) 2026 PIETOOLS Team
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% If you modify this code, document all changes carefully and include date
% authorship, and a brief description of modifications
%
% Initial coding MMP, 09/29/2026. P(...) returned P unchanged (see NOTES);
%                it is now an error. 'matlab.mixin.Scalar' would give the
%                error without an overload, but it seals size, horzcat,
%                vertcat, ctranspose and transpose, which this class
%                overloads, so the class would not load (measured, R2025b).

if strcmp(s(1).type,'()')
    error('copvar:parenIndex',['Paren indexing P(...) of a copvar is not '...
        'implemented: component indexing of containers does not exist yet, '...
        'and MATLAB''s default would return the whole container. Use '...
        'P.C{i,j} for block (i,j).'])
end
% The builtin called from this method has the class's own access, so it
% would read protected properties that P.name outside the class may not.
% Raise the builtin's error for them, same identifier and text (measured).
% Names come from the metaclass, once.
persistent hidden
if ~iscell(hidden)
    mc = ?copvar;   pl = mc.PropertyList;
    hidden = {pl(~cellfun(@(a) isequal(a,'public'),{pl.GetAccess})).Name};
end
if strcmp(s(1).type,'.') && any(strcmp(s(1).subs,hidden))
    error(message('MATLAB:class:GetProhibited',s(1).subs,'''copvar'''))
end
[varargout{1:nargout}] = builtin('subsref',P,s);

end
