function nm = t1d_ownnames()                                                % CC, 09/22/2026
% t1d_ownnames -- every function name this directory provides.
%
% Used twice: t1d_path removes out-of-tree path entries that provide any of
% them (defect B6, mechanism 2), and T0 asserts each resolves to exactly one
% file.  Keep it in step with the directory contents -- T0 also checks that,
% so a file added here without a name added there fails the hygiene test
% rather than going unwatched.
nm = [t1d_corefiles(), ...
      {'gate1d','opcheck','op2gal','polyeval2','restrict_solve_1d', ...
       'build_stab_st','rd_pie_lam', ...
       't1d_bm','t1d_build','t1d_ipm','t1d_set','t1d_path','t1d_subfun', ...
       't1d_codelines','t1d_corefiles','t1d_ownnames','t1d_whichcore', ...
       'run_regression_1d'}];
end
