function Pop = rand_mopvar(spaces,dims,dom,deg,dnsty,occ)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% POP = RAND_MOPVAR(SPACES,DIMS,DOM,DEG,DNSTY,OCC) generates a random
% 'mopvar' container over the given output and input spaces.
%
% INPUTS
% - spaces: struct with fields 'out' and 'in'. spaces.out is a 1 x M cell
%           whose i-th entry is a cellstr naming the spatial variables of
%           the i-th output space s^i; spaces.in is the 1 x N analogue for
%           the input spaces. An empty cellstr means a finite-dimensional
%           (R^n) space, which is legal and is what every PIE has;
% - dims:   struct with fields 'out' (M x 1) and 'in' (N x 1), the component
%           counts q_i and p_j. A scalar is expanded;
% - dom:    1 x 2 array [a,b], applied to every spatial variable, or an
%           nv x 2 array together with a cellstr third field spaces.vars
%           giving the variable order. The 1 x 2 form is the common case;
% - deg:    scalar maximal monomial degree in each variable, or a struct
%           with fields 'out' and 'in' for different degrees per side;
% - dnsty:  scalar in (0,1], density of the sparse parameter matrices;
% - occ:    optional M x N logical; false entries are left as structurally
%           zero blocks. Defaults to all true. Every row and every column
%           must keep at least one populated block, since the container
%           derives that row's space and dimension from it;
%
% OUTPUTS
% - Pop:    'mopvar' object with 'sopvar' blocks;
%
% EXAMPLE - the 1D PIE structure, R^2 x L2^3[s] to itself:
%   spaces = struct('out',{{ {}, {'s'} }},'in',{{ {}, {'s'} }});
%   dims   = struct('out',[2;3],'in',[2;3]);
%   Pop    = rand_mopvar(spaces,dims,[0,1],2,0.6);
%
% NOTES
% Blocks are generated by 'rand_sopvar', so the monomial degree SETS are
% themselves random subsets of 0..deg, per variable and per side. That is
% deliberate: a generator that gave every block the full basis of degree
% deg would never exercise the basis-union paths in plus, mtimes and eq,
% which is where the container's cost lives.
%
% See also RAND_MDOPVAR, RAND_SOPVAR, MOPVAR, OPVAR2MOPVAR.
%
% For support, contact M. Peet, Arizona State University at mpeet@asu.edu

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PIETOOLS - rand_mopvar
%
% Copyright (C) 2026 PIETOOLS Team
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% If you modify this code, document all changes carefully and include date
% authorship, and a brief description of modifications
%
% Initial coding MMP, 09/18/2026

if ~isstruct(spaces) || ~isfield(spaces,'out') || ~isfield(spaces,'in')
    error('rand_mopvar:badSpaces',...
        "Spaces must be a struct with fields 'out' and 'in'.")
end
M = numel(spaces.out);      N = numel(spaces.in);
if nargin<5 || isempty(dnsty),  dnsty = 0.6;    end
if nargin<6 || isempty(occ),    occ = true(M,N);    end
if isscalar(deg),   deg = struct('out',deg,'in',deg);   end
dim_out = expand(dims.out,M,'dims.out');
dim_in  = expand(dims.in ,N,'dims.in');

% Reject an all-empty row or column here rather than letting the container
% report it, so the message names the generator argument at fault.
if M>0 && N>0
    if any(~any(occ,2))
        error('rand_mopvar:emptyRow',...
            'occ leaves row(s) %s empty; each row needs one populated block.',...
            mat2str(find(~any(occ,2))'))
    end
    if any(~any(occ,1))
        error('rand_mopvar:emptyColumn',...
            'occ leaves column(s) %s empty; each column needs one populated block.',...
            mat2str(find(~any(occ,1))))
    end
end

C = cell(M,N);
for i = 1:M
    for j = 1:N
        if ~occ(i,j),   continue,   end
        vs = struct('out',{spaces.out{i}},'in',{spaces.in{j}});
        ds = struct('out',dom_rows(dom,vs.out,spaces),...
                    'in' ,dom_rows(dom,vs.in ,spaces));
        gs = struct('out',deg.out*ones(1,numel(vs.out)),...
                    'in' ,deg.in *ones(1,numel(vs.in )));
        C{i,j} = rand_sopvar([dim_out(i),dim_in(j)],vs,ds,gs,dnsty);
    end
end
Pop = mopvar(C);

end

% ------------------------------------------------------------------------
function v = expand(v,n,nm)
if isscalar(v),     v = v*ones(n,1);    end
if numel(v)~=n
    error('rand_mopvar:badDims','%s must have %d entries.',nm,n)
end
v = v(:);
end

function d = dom_rows(dom,v,spaces)
% One domain row per variable of this space, in THIS BLOCK'S variable order.
%
% A 1x2 dom is shared by every variable. Otherwise dom is nv x 2 indexed by
% spaces.vars and is looked up BY NAME: a block orders its variables
% [S2,S3] on the output side and [S3,S1] on the input side, so its order is
% not the registry order and positional indexing would hand a variable
% someone else's domain - which the container would then reject as a domain
% conflict, or worse would not, if the two happened to agree.
if size(dom,1)==1
    d = repmat(dom,numel(v),1);
    return
end
if ~isfield(spaces,'vars')
    error('rand_mopvar:noVarList',...
        ['A dom with more than one row needs spaces.vars, a cellstr giving '...
         'the variable each row belongs to.'])
end
d = zeros(numel(v),2);
for k = 1:numel(v)
    idx = find(strcmp(spaces.vars,v{k}),1);
    if isempty(idx)
        error('rand_mopvar:unknownVar',...
            'Variable ''%s'' is not listed in spaces.vars.',v{k})
    end
    d(k,:) = dom(idx,:);
end
end
