function obj = subsasgn(obj,s,varargin)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OBJ = SUBSASGN(OBJ,S,VAL) assigns into a 'sopvar': dot assignment is the
% builtin, paren assignment OBJ(...) = VAL is an error.
%
% INPUTS
% - obj:  'sopvar' object, or [] when OBJ(...) = VAL creates a variable;
% - s:    substruct of the indexing expression, generated by MATLAB;
% - varargin: the value(s) assigned; more than one for a comma-list
%           assignment such as [P.params{1:2}] = deal(a,b);
%
% OUTPUTS
% - obj:  the modified object.
%
% NOTES
% Why an error: 'subsref' makes P(I,J) a component slice, but the builtin
% assignment S(2,1) = P builds a 2 x 1 ARRAY of sopvar objects, on which
% the overloaded 'size' errors and every other method misreads it. Assigning
% components, P(I,J) = X, is not implemented. Dot assignment (P.params{k} =
% X, P.dims = ...) is unchanged; assigning into a property directly still
% bypasses the constructor and its canonical form, as before. Assigning a
% block INTO a cell or a struct field (C{i,j} = P) does not call this
% method.
%
% Cost (measured, R2025b): called for every assignment into a sopvar
% outside the class methods.
% - A direct edit of a local block is in place: P.params{1}(5,5) = v on a
%   22.9 MB params{1} took 22 us, against 9 us without this method.
% - A NESTED indexed edit of a block held in a container, a cell or a
%   struct field, or made from a method of another class, COPIES the
%   edited leaf on every assignment: MATLAB passes the block to this method
%   as a shared temporary. P.C{i,j}.params{k}(r,c) = v is O(numel) of
%   params{k}: 1.07 ms on the 22.9 MB params{1} in a copvar, a full copy
%   (1.1 ms), against 8 us without the overloads. The cell, struct and
%   method cases were measured on sdopvar blocks (@sdopvar/subsasgn).
% - For such an edit, extract, clear, edit, reinsert, which edits the
%   block in place (65 us on the 22.9 MB params{1}):
%       X = P.C{i,j};  P.C{i,j} = [];  X.params{k}(r,c) = v;  P.C{i,j} = X;
%
% See also SUBSREF, SOPVAR.
%
% For support, contact M. Peet, Arizona State University at mpeet@asu.edu

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PIETOOLS - subsasgn(sopvar)
%
% Copyright (C) 2026 PIETOOLS Team
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% If you modify this code, document all changes carefully and include date
% authorship, and a brief description of modifications
%
% Initial coding MMP, 09/29/2026. S(2,1) = P built an object array (see
%                NOTES); it is now an error. 'matlab.mixin.Scalar' would
%                give the error without an overload, but it seals size,
%                horzcat, vertcat, ctranspose and transpose, which this
%                class overloads, so the class would not load (measured,
%                R2025b).

if strcmp(s(1).type,'()')
    error('sopvar:parenAssign',['Paren assignment P(...) = X is not '...
        'supported for sopvar: it would build an array of operators, and '...
        'component assignment is not implemented. P(I,J) (reference) '...
        'slices components; assign properties with P.name = X.'])
end
% The builtin called from this method has the class's own access, so it
% would set protected properties (vars_S1, dom_1, ...) that P.name = X
% outside the class may not. Raise the builtin's error for them, same
% identifier and text (measured). Names come from the metaclass, once.
persistent hidden
if ~iscell(hidden)
    mc = ?sopvar;   pl = mc.PropertyList;
    hidden = {pl(~cellfun(@(a) isequal(a,'public'),{pl.SetAccess})).Name};
end
if strcmp(s(1).type,'.') && any(strcmp(s(1).subs,hidden))
    error(message('MATLAB:class:SetProhibited',s(1).subs,'''sopvar'''))
end
obj = builtin('subsasgn',obj,s,varargin{:});

end
