function [out,varargout] = subsref(obj,s)                                   % MMP, 09/29/2026
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% out=subsref(Pbop,s) used for subscripted indexing of the operator 
% P: R^p x L2^q to R^m x L2^n
% 
% INPUT
% obj: sopvar class object to slice
% s: structure of indices used for reference (auto generated by matlab
% based on subscript expression
% 
% OUTPUT
% out: sopvar object (if slicing the operator), otherwise depends on the
% subscript expression
%
% NOTES:
% For support, contact M. Peet, Arizona State University at mpeet@asu.edu
% or S. Shivakumar at sshivak8@asu.edu

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PIETools - subsref
%
% Copyright (C)2025  PIETOOLS Team
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% If you modify this code, document all changes carefully and include date
% authorship, and a brief description of modifications
%
% Initial coding AT 01/26/2026
% updated to new sopvar AT 05/18/26
% Correct order ZL and ZR, DJ 06/08/2026
% Return every element of a '.' comma list, MMP, 09/29/2026. With the one
%   output 'out', {P.params{:}}, [P.params{:}] and f(P.ZL{:}) silently kept
%   the first element only, and P.C{i,j}.params{:} through a container
%   raised MATLAB:TooManyOutputs. A '.' read now returns nargout values,
%   the builtin count set by 'numArgumentsFromSubscript'; the one-value
%   read and '()' run the same lines as before, so their outputs and cost
%   are unchanged. The signature was
% function out = subsref(obj,s)                                             % MMP, 09/29/2026 (was)
% Continue indexing after a slice, MMP, 09/29/2026: P(I,J).dims silently
%   returned the slice (the tail was dropped); it now continues, as in
%   'sdopvar'. A slice followed by a comma-list brace, e.g. {P(I,J).ZL{:}},
%   is refused: a '()' read gets one output, so the list would keep only
%   its first element.

switch s(1).type
    case '.'
        if nargout~=1                                                       % MMP, 09/29/2026
            % A comma list: nargout is its length (0 for an empty list;     % MMP, 09/29/2026
            % an explicit subsref(P,s) statement also has 0 and returns     % MMP, 09/29/2026
            % the one value as 'ans', as before).                           % MMP, 09/29/2026
            [varargout{1:nargout}] = builtin('subsref',obj,s);              % MMP, 09/29/2026
            if ~isempty(varargout)                                          % MMP, 09/29/2026
                out = varargout{1};  varargout(1) = [];                     % MMP, 09/29/2026
            end                                                             % MMP, 09/29/2026
            return                                                          % MMP, 09/29/2026
        end                                                                 % MMP, 09/29/2026
        out = builtin('subsref',obj,s);
    case '()'
        % A comma-list brace after the slice cannot be served (one output). % MMP, 09/29/2026
        for k = 2:numel(s)                                                  % MMP, 09/29/2026
            if strcmp(s(k).type,'{}') && ~all(cellfun(@(x) isscalar(x) && (isnumeric(x) || islogical(x)),s(k).subs)) % MMP, 09/29/2026
                error('sopvar:parenThenList','Slice first, then read the list: Y = P(I,J); Y.field{...}.') % MMP, 09/29/2026
            end                                                             % MMP, 09/29/2026
        end                                                                 % MMP, 09/29/2026
        indr = s(1).subs{1}; %output
        indc = s(1).subs{2}; %input
        dim_old=obj.dims;

        nr1_old=dim_old(1); % output dimension
        nr2_old=dim_old(2); % input dimension

        % Allow indices to be specified as e.g. (i,:);
        if strcmp(indr,':') && strcmp(indc,':')
            out = obj;
            return
        end
        if strcmp(indr,':')
            indr = (1:nr1_old);
        end
        if strcmp(indc,':')
            indc = (1:nr2_old);
        end


        if size(indr, 1) == 1
            indr = indr';
        end
        if size(indc, 1) == 1
            indc = indc';
        end

        if max(indr) > obj.dims(1)
            error('index exceeds the number of rows in the original sopvar')
        end
        if max(indc) > obj.dims(2)
            error('index exceeds the number of columns in the original sopvar')
        end

        % Construct the sliced opvar
        vars = obj.vars;
        dom  = obj.dom;
        dims = obj.dims;
        ZL   = obj.ZL;
        ZR   = obj.ZR;
        deg_r = cellfun(@(x) length(x), ZL, 'UniformOutput',true); % rows
        deg_c = cellfun(@(x) length(x), ZR, 'UniformOutput',true); % columns

        n_mon_r = prod(deg_r);
        n_mon_c = prod(deg_c);


        dims = [length(indr), length(indc)];
        
        subsref_params = obj.params; 
        
        % rows
        Loc_L_R = n_mon_r*(indr - 1) + 1; % starting location of C rows
        Loc_L_R= [kron(Loc_L_R, ones(n_mon_r, 1)), kron( ones(length(Loc_L_R), 1), (0:(n_mon_r-1))' )];
        Loc_L_R = sum(Loc_L_R, 2);
        
        %columns
        Loc_L_C = n_mon_c*(indc - 1) + 1; % starting location of C columns
        Loc_L_C= [kron(Loc_L_C, ones(n_mon_c, 1)), kron( ones(length(Loc_L_C), 1), (0:(n_mon_c-1))' )];
        Loc_L_C = sum(Loc_L_C, 2);

        for ii = 1:numel(subsref_params)
            subsref_params{ii} = subsref_params{ii}(Loc_L_R, Loc_L_C);
        end

        out = sopvar(subsref_params, obj.vars, ZL, ZR, obj.dom, dims);      % MMP, 08/29/2026

        % Continue any further indexing, e.g. P(1,1).dims, as sdopvar does; % MMP, 09/29/2026
        % the tail used to be dropped and the slice returned instead.       % MMP, 09/29/2026
        if numel(s)>1                                                       % MMP, 09/29/2026
            out = subsref(out,s(2:end));                                    % MMP, 09/29/2026
        end                                                                 % MMP, 09/29/2026

    case '{}'
        error('Not a valid indexing expression')
end
end
