function obj = subsasgn(obj,s,varargin)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OBJ = SUBSASGN(OBJ,S,VAL) assigns into a 'sdopvar': dot assignment is the
% builtin, paren assignment OBJ(...) = VAL is an error.
%
% INPUTS
% - obj:  'sdopvar' object, or [] when OBJ(...) = VAL creates a variable;
% - s:    substruct of the indexing expression, generated by MATLAB;
% - varargin: the value(s) assigned; more than one for a comma-list
%           assignment such as [P.Zd{1:2}] = deal(a,b);
%
% OUTPUTS
% - obj:  the modified object.
%
% NOTES
% Why an error: 'subsref' makes P(I,J) a component slice, but the builtin
% assignment S(2,1) = P builds a 2 x 1 ARRAY of sdopvar objects, on which
% the overloaded 'size' errors and every other method misreads it. Assigning
% components, P(I,J) = X, is not implemented. Dot assignment
% (P.params.A{k} = X, P.Zd = ...) is unchanged; assigning into a property
% directly still bypasses the constructor and its canonical form, as
% before. Assigning a block INTO a cell or a struct field (C{i,j} = P) does
% not call this method.
%
% Cost (measured, R2025b): called for every assignment into an sdopvar
% outside the class methods.
% - A direct edit of a local block is in place: P.params.B{1}(5,1) = v
%   took 15 / 18 / 46 us at q = 1e5 / 5e5 / 2e6, against 0.4 / 2 / 31 us
%   without this method; the difference is the call, flat in q.
% - A NESTED indexed edit of a block held in a container, a cell or a
%   struct field, or made from a method of another class, COPIES the
%   edited leaf on every assignment: MATLAB passes the block to this method
%   as a shared temporary. P.C{i,j}.params.B{k}(r,c) = v is O(nnz(B{k}))
%   (1.1 ms at q = 2e6, nnz 3.9e5) and P.C{i,j}.Zd{i} = name is O(q)
%   (23 ms at q = 2e6), against 31 us and 1.4 us without the overloads.
% - For such an edit, extract, clear, edit, reinsert, which edits the
%   block in place (53-93 us per edit for q = 1e5 to 2e6):
%       X = P.C{i,j};  P.C{i,j} = [];  X.params.B{k}(r,c) = v;  P.C{i,j} = X;
%
% See also SUBSREF, SDOPVAR.
%
% For support, contact M. Peet, Arizona State University at mpeet@asu.edu

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PIETOOLS - subsasgn(sdopvar)
%
% Copyright (C) 2026 PIETOOLS Team
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% If you modify this code, document all changes carefully and include date
% authorship, and a brief description of modifications
%
% Initial coding MMP, 09/29/2026. S(2,1) = P built an object array (see
%                NOTES); it is now an error. 'matlab.mixin.Scalar' would
%                give the error without an overload, but it seals size,
%                horzcat, vertcat, ctranspose and transpose, which this
%                class overloads, so the class would not load (measured,
%                R2025b).

if strcmp(s(1).type,'()')
    error('sdopvar:parenAssign',['Paren assignment P(...) = X is not '...
        'supported for sdopvar: it would build an array of operators, and '...
        'component assignment is not implemented. P(I,J) (reference) '...
        'slices components; assign properties with P.name = X.'])
end
% The builtin called from this method has the class's own access, so it
% would set any non-public property that P.name = X outside the class may
% not (sdopvar has none today). Raise the builtin's error for them, same
% identifier and text (measured). Names come from the metaclass, once.
persistent hidden
if ~iscell(hidden)
    mc = ?sdopvar;  pl = mc.PropertyList;
    hidden = {pl(~cellfun(@(a) isequal(a,'public'),{pl.SetAccess})).Name};
end
if strcmp(s(1).type,'.') && any(strcmp(s(1).subs,hidden))
    error(message('MATLAB:class:SetProhibited',s(1).subs,'''sdopvar'''))
end
obj = builtin('subsasgn',obj,s,varargin{:});

end
