function out = subsref(obj,s)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% out=subsref(Pbop,s) used for subscripted indexing of the operator 
% P: R^p x L2^q to R^m x L2^n
% 
% INPUT
% obj: sopvar class object to slice
% s: structure of indices used for reference (auto generated by matlab
% based on subscript expression
% 
% OUTPUT
% out: sopvar object (if slicing the operator), otherwise depends on the
% subscript expression
%
% NOTES:
% For support, contact M. Peet, Arizona State University at mpeet@asu.edu
% or S. Shivakumar at sshivak8@asu.edu

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PIETools - subsref
%
% Copyright (C)2025  PIETOOLS Team
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% If you modify this code, document all changes carefully and include date
% authorship, and a brief description of modifications
%
% Initial coding AT 01/26/2026

switch s(1).type
    case '.'
        out = builtin('subsref',obj,s);
    case '()'
        indr = s(1).subs{1}; %output
        indc = s(1).subs{2}; %input
        dim_old=obj.dims;

        nr1_old=dim_old(1); % output dimension
        nr2_old=dim_old(2); % input dimension

        % Allow indices to be specified as e.g. (i,:);
        if strcmp(indr,':') && strcmp(indc,':')
            out = obj;
            return
        end
        if strcmp(indr,':')
            indr = (1:nr1_old);
        end
        if strcmp(indc,':')
            indc = (1:nr2_old);
        end


        if size(indr, 1) == 1
            indr = indr';
        end
        if size(indc, 1) == 1
            indc = indc';
        end

        if max(indr) > obj.dims(1)
            error('index exceeds the number of rows in the original sopvar')
        end
        if max(indc) > obj.dims(2)
            error('index exceeds the number of columns in the original sopvar')
        end

        % Construct the sliced opvar
        vars_S1 = obj.vars_S1;
        vars_S2 = obj.vars_S2;
        vars_S3 = obj.vars_S3;
        dom_3 = obj.dom_3;
        dom_2 = obj.dom_2;
        dom_1 = obj.dom_1;
        dims = [length(indr), length(indc)];
        
        subsref_params = obj.params; 

        for ii = 1:numel(subsref_params)
            subsref_params{ii} = subsref_params{ii}(indr, indc);
        end

        out = sopvar(vars_S3,dom_3,dims,subsref_params,vars_S1,dom_1,vars_S2,dom_2);


    case '{}'
        error('Not a valid indexing expression')
end
end
