function out = subsref(obj,s)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% out=subsref(Pbop,s) used for subscripted indexing of the operator 
% P: R^p x L2^q to R^m x L2^n
% 
% INPUT
% obj: sopvar class object to slice
% s: structure of indices used for reference (auto generated by matlab
% based on subscript expression
% 
% OUTPUT
% out: sopvar object (if slicing the operator), otherwise depends on the
% subscript expression
%
% NOTES:
% For support, contact M. Peet, Arizona State University at mpeet@asu.edu
% or S. Shivakumar at sshivak8@asu.edu

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PIETools - subsref
%
% Copyright (C)2025  PIETOOLS Team
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% If you modify this code, document all changes carefully and include date
% authorship, and a brief description of modifications
%
% Initial coding AT 01/26/2026
% updated to new sopvar AT 05/18/26

switch s(1).type
    case '.'
        out = builtin('subsref',obj,s);
    case '()'
        indr = s(1).subs{1}; %output
        indc = s(1).subs{2}; %input
        dim_old=obj.dims;

        nr1_old=dim_old(1); % output dimension
        nr2_old=dim_old(2); % input dimension

        % Allow indices to be specified as e.g. (i,:);
        if strcmp(indr,':') && strcmp(indc,':')
            out = obj;
            return
        end
        if strcmp(indr,':')
            indr = (1:nr1_old);
        end
        if strcmp(indc,':')
            indc = (1:nr2_old);
        end


        if size(indr, 1) == 1
            indr = indr';
        end
        if size(indc, 1) == 1
            indc = indc';
        end

        if max(indr) > obj.dims(1)
            error('index exceeds the number of rows in the original sopvar')
        end
        if max(indc) > obj.dims(2)
            error('index exceeds the number of columns in the original sopvar')
        end

        % Construct the sliced opvar
        vars = obj.vars;
        dom  = obj.dom;
        dims = obj.dims;
        ZL   = obj.ZL;
        ZR   = obj.ZR;
        deg_r = cellfun(@(x) length(x), ZL, 'UniformOutput',true); % rows
        deg_c = cellfun(@(x) length(x), ZR, 'UniformOutput',true); % columns

        n_mon_r = prod(deg_r);
        n_mon_c = prod(deg_c);


        dims = [length(indr), length(indc)];
        
        subsref_params = obj.params; 
        
        % rows
        Loc_L_R = n_mon_r*(indr - 1) + 1; % starting location of C rows
        Loc_L_R= [kron(Loc_L_R, ones(n_mon_r, 1)), kron( ones(length(Loc_L_R), 1), (0:(n_mon_r-1))' )];
        Loc_L_R = sum(Loc_L_R, 2);
        
        %columns
        Loc_L_C = n_mon_c*(indc - 1) + 1; % starting location of C columns
        Loc_L_C= [kron(Loc_L_C, ones(n_mon_c, 1)), kron( ones(length(Loc_L_C), 1), (0:(n_mon_c-1))' )];
        Loc_L_C = sum(Loc_L_C, 2);

        for ii = 1:numel(subsref_params)
            subsref_params{ii} = subsref_params{ii}(Loc_L_R, Loc_L_C);
        end

        out = sopvar(subsref_params, obj.vars, obj.ZL, obj.ZR, obj.dom, dims); 


    case '{}'
        error('Not a valid indexing expression')
end
end
